SET search_path TO projet;


-- Schéma

DROP SCHEMA IF EXISTS projet CASCADE;
CREATE SCHEMA projet AUTHORIZATION projet;
GRANT ALL PRIVILEGES ON SCHEMA projet TO projet;


-- Tables

CREATE TABLE compte (
	IdCompte		INT			 	NOT NULL	GENERATED BY DEFAULT AS IDENTITY,
	Pseudo			VARCHAR(25)		NOT NULL,
	MotDePasse		VARCHAR(25) 	NOT NULL,
	Email			VARCHAR(100)	NOT NULL,
	PRIMARY KEY (IdCompte)
);
CREATE UNIQUE INDEX idx_compte_pseudo ON compte (Pseudo ASC);

CREATE TABLE role (
	IdCompte		INT				NOT NULL,
	Role			VARCHAR(20)		NOT NULL,
	CHECK( Role IN ('ADMINISTRATEUR','UTILISATEUR') ),	
	FOREIGN KEY (IdCompte) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdCompte, Role)
);

CREATE TABLE ouvrage (
	IdOuvrage		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	IdProprietaire			INT 	NOT NULL,
	Titre			VARCHAR(20)		NOT NULL,
	DateParution 	DATE 			NOT NULL,
	Auteur			VARCHAR(30)		NOT NULL,
	FOREIGN KEY (IdProprietaire) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdOuvrage)
);

CREATE TABLE categorie_ouvrage (
	IdOuvrage		INT				NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	Categorie		VARCHAR(20)		NOT NULL,
	FOREIGN KEY (IdOuvrage) REFERENCES ouvrage (IdOuvrage),
	PRIMARY KEY (IdOuvrage)
);

CREATE TABLE demande_emprunt (
	IdDemandeEmprunt		INT		NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	IdEmprunteur			INT 	NOT NULL,
	IdProprietaire			INT 	NOT NULL,
	IdOuvrage				INT 	NOT NULL,
	Statut					VARCHAR(20)		NOT NULL,
	DateEmprunt			 	DATE 			NOT NULL,
	CHECK( Statut IN ('EN ATTENTE','ACCEPTEE', 'REFUSEE', 'RENDUE') ),	
	FOREIGN KEY (IdEmprunteur) REFERENCES compte (IdCompte),
	FOREIGN KEY (IdProprietaire) REFERENCES compte (IdCompte),
	FOREIGN KEY (IdOuvrage) REFERENCES ouvrage (IdOuvrage),
	PRIMARY KEY (IdDemandeEmprunt)
);

CREATE TABLE demande_amis (
	IdDemandeAmis			INT		NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	IdEnvoyeur				INT 	NOT NULL,
	IdReceveur				INT 	NOT NULL,
	Statut					VARCHAR(20)		NOT NULL,
	DateDemande			 	DATE 			NOT NULL,
	CHECK( Statut IN ('EN ATTENTE','ACCEPTEE', 'REFUSEE') ),	
	FOREIGN KEY (IdEnvoyeur) REFERENCES compte (IdCompte),
	FOREIGN KEY (IdReceveur) REFERENCES compte (IdCompte),
	PRIMARY KEY (IdDemandeAmis)
);





